# -*- coding: utf-8 -*-
"""assoignment06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzFF-CDHWryRaNhlRWbB68_DUXB13dih
"""



"""1. Using self
Assignment:
Create a class Student with attributes name and marks. Use the self keyword to initialize these values via a constructor. Add a method display() that prints student details
"""

class Student():
  def __init__(self,name,marks):
    self.name = name
    self.marks = marks
  def display(self):
   print(f"Name: {self.name}")
   print(f"Marks: {self.marks}")

student1 = Student("Sana", 31)
student1.display()

"""2. Using cls
Assignment:
Create a class Counter that keeps track of how many objects have been created. Use a class variable and a class method with cls to manage and display the count.
"""

class Counter:
    # Class variable to keep track of number of instances
    count = 0

    def __init__(self):
        # Increment the counter when a new object is created
        Counter.count += 1

    @classmethod
    def display_count(cls):
        # Class method to display the current count
        print(f"Number of Counter objects created: {cls.count}")


# Example usage:
a = Counter()
b = Counter()
c = Counter()

Counter.display_count()  # Output: Number of Counter objects created: 3

"""
3. Public Variables and Methods
Assignment:
Create a class Car with a public variable brand and a public method start(). Instantiate the class and access both from outside the class.

"""

class Car:
    def __init__(self, brand):
        # Public instance variable
        self.brand = brand

    # Public method
    def start(self):
        print(f"The {self.brand} car has started.")


# Instantiate the class
my_car = Car("Toyota")

# Access the public variable
print(my_car.brand)  # Output: Toyota

# Call the public method
my_car.start()        # Output: The Toyota car has started.

"""4. Class Variables and Class Methods
Assignment:
Create a class Bank with a class variable bank_name. Add a class method change_bank_name(cls, name) that allows changing the bank name. Show that it affects all instances.
"""

class Bank:
    # Class variable
    bank_name = "Default Bank"

    def __init__(self, account_holder):
        self.account_holder = account_holder

    @classmethod
    def change_bank_name(cls, name):
        cls.bank_name = name

    def display(self):
        print(f"Account Holder: {self.account_holder}, Bank: {Bank.bank_name}")


# Create instances
acc1 = Bank("Sana")
acc2 = Bank("Sarwar")

# Display initial bank name
acc1.display()  # Output: Account Holder: Alice, Bank: Default Bank
acc2.display()  # Output: Account Holder: Bob, Bank: Default Bank

# Change the bank name using class method
Bank.change_bank_name("Global Trust Bank")

# Display updated bank name from both instances
acc1.display()  # Output: Account Holder: Alice, Bank: Global Trust Bank
acc2.display()  # Output: Account Holder: Bob, Bank: Global Trust Bank

"""
5. Static Variables and Static Methods
Assignment:
Create a class MathUtils with a static method add(a, b) that returns the sum. No class or instance variables should be used."""

class MathUtils:
    @staticmethod
    def add(a, b):
        return a + b


# Example usage
result = MathUtils.add(5, 7)
print("Sum:", result)  # Output: Sum: 12

"""6. Constructors and Destructors
Assignment:
Create a class Logger that prints a message when an object is created (constructor) and another message when it is destroyed (destructor).
"""

class Logger:
    def __init__(self):
        print("Logger initialized. Object created.")

    def __del__(self):
        print("Logger object destroyed.")


# Example usage
log = Logger()

# Force deletion to see destructor effect immediately (optional in scripts)
del log

"""7. Access Modifiers: Public, Private, and Protected
Assignment:
Create a class Employee with:

a public variable name,

a protected variable _salary, and

a private variable __ssn.

Try accessing all three variables from an object of the class and document what happens.
"""

class Employee:
    def __init__(self, name, salary, ssn):
        self.name = name            # Public
        self._salary = salary       # Protected (convention)
        self.__ssn = ssn            # Private (name mangled)

    def show_info(self):
        print(f"Name: {self.name}")
        print(f"Salary: {self._salary}")
        print(f"SSN: {self.__ssn}")

"""8. The super() Function
Assignment:
Create a class Person with a constructor that sets the name. Inherit a class Teacher from it, add a subject field, and use super() to call the base class constructor.
"""

# Base class
class Person:
    def __init__(self, name):
        self.name = name
        print(f"Person constructor called. Name: {self.name}")

# Derived class
class Teacher(Person):
    def __init__(self, name, subject):
        super().__init__(name)  # Call the base class constructor
        self.subject = subject
        print(f"Teacher constructor called. Subject: {self.subject}")


# Example usage
t = Teacher("Alice Smith", "Mathematics")

"""9. Abstract Classes and Methods
Assignment:
Use the abc module to create an abstract class Shape with an abstract method area(). Inherit a class Rectangle that implements area().
"""

from abc import ABC, abstractmethod

# Abstract base class
class Shape(ABC):
    @abstractmethod
    def area(self):
        pass  # Abstract method, must be implemented in subclasses

# Concrete subclass
class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height


# Example usage
rect = Rectangle(5, 10)
print("Area of rectangle:", rect.area())  # Output: Area of rectangle: 50

"""10. Instance Methods
Assignment:
Create a class Dog with instance variables name and breed. Add an instance method bark() that prints a message including the dog's name.


"""

class Dog:
    def __init__(self, name, breed):
        self.name = name    # Instance variable
        self.breed = breed  # Instance variable

    def bark(self):
        print(f"{self.name} the {self.breed} says: Woof!")


# Example usage
dog1 = Dog("Buddy", "Golden Retriever")
dog1.bark()  # Output: Buddy the Golden Retriever says: Woof!

"""11. Class Methods
Assignment:
Create a class Book with a class variable total_books. Add a class method increment_book_count() to increase the count when a new book is added.


"""

class Book:
    # Class variable to track the number of books
    total_books = 0

    def __init__(self, title, author):
        self.title = title
        self.author = author
        Book.increment_book_count()  # Increment the count when a new book is created

    @classmethod
    def increment_book_count(cls):
        cls.total_books += 1  # Increase the count of total books

    @classmethod
    def display_total_books(cls):
        print(f"Total books: {cls.total_books}")


# Example usage
book1 = Book("1984", "George Orwell")
book2 = Book("To Kill a Mockingbird", "Harper Lee")
book3 = Book("Pride and Prejudice", "Jane Austen")

Book.display_total_books()  # Output: Total books: 3

"""12. Static Methods
Assignment:
Create a class TemperatureConverter with a static method celsius_to_fahrenheit(c) that returns the Fahrenheit value.
"""

class TemperatureConverter:
    @staticmethod
    def celsius_to_fahrenheit(c):
        return (c * 9/5) + 32


# Example usage
celsius_temp = 25
fahrenheit_temp = TemperatureConverter.celsius_to_fahrenheit(celsius_temp)
print(f"{celsius_temp}°C is equal to {fahrenheit_temp}°F")  # Output: 25°C is equal to 77.0°F

"""13. Composition
Assignment:
Create a class Engine and a class Car. Use composition by passing an Engine object to the Car class during initialization. Access a method of the Engine class via the Car class.
"""

class Engine:
    def __init__(self, engine_type):
        self.engine_type = engine_type

    def start(self):
        print(f"The {self.engine_type} engine has started.")

    def stop(self):
        print(f"The {self.engine_type} engine has stopped.")


class Car:
    def __init__(self, brand, engine):
        self.brand = brand
        self.engine = engine  # Composition: Car contains an Engine object

    def start_car(self):
        print(f"{self.brand} car is starting.")
        self.engine.start()  # Accessing the Engine's start method via Car

    def stop_car(self):
        print(f"{self.brand} car is stopping.")
        self.engine.stop()  # Accessing the Engine's stop method via Car


# Example usage
engine = Engine("V8")
car = Car("Ford Mustang", engine)

car.start_car()  # Output: Ford Mustang car is starting. The V8 engine has started.
car.stop_car()   # Output: Ford Mustang car is stopping. The V8 engine has stopped.

"""14. Aggregation
Assignment:
Create a class Department and a class Employee. Use aggregation by having a Department object store a reference to an Employee object that exists independently of it.
"""

class Employee:
    def __init__(self, name, role):
        self.name = name
        self.role = role

    def display_info(self):
        print(f"Employee Name: {self.name}, Role: {self.role}")


class Department:
    def __init__(self, department_name, employee):
        self.department_name = department_name
        self.employee = employee  # Aggregation: Department stores reference to an Employee object

    def display_department_info(self):
        print(f"Department: {self.department_name}")
        self.employee.display_info()  # Accessing Employee's method via Department


# Example usage
emp = Employee("Alice", "Software Engineer")  # Employee object created independently
dept = Department("Engineering", emp)         # Department object stores reference to Employee

dept.display_department_info()

"""15. Method Resolution Order (MRO) and Diamond Inheritance
Assignment:
Create four classes:

A with a method show(),

B and C that inherit from A and override show(),

D that inherits from both B and C.

Create an object of D and call show() to observe MRO.
"""

class A:
    def show(self):
        print("Method from class A")

class B(A):
    def show(self):
        print("Method from class B")

class C(A):
    def show(self):
        print("Method from class C")

class D(B, C):  # Inherits from both B and C
    pass

# Create an object of D and call show()
d = D()
d.show()

"""16. Function Decorators
Assignment:
Write a decorator function log_function_call that prints "Function is being called" before a function executes. Apply it to a function say_hello().
"""

# Define the decorator
def log_function_call(func):
    def wrapper(*args, **kwargs):
        print("Function is being called")
        return func(*args, **kwargs)
    return wrapper

# Apply the decorator to the function say_hello
@log_function_call
def say_hello():
    print("Hello!")

# Call the function
say_hello()

"""17. Class Decorators
Assignment:
Create a class decorator add_greeting that modifies a class to add a greet() method returning "Hello from Decorator!". Apply it to a class Person.


"""

# Define the class decorator
def add_greeting(cls):
    def greet(self):
        return "Hello from Decorator!"
    cls.greet = greet  # Add the greet method to the class
    return cls

# Apply the class decorator to the Person class
@add_greeting
class Person:
    def __init__(self, name):
        self.name = name

# Create an instance of Person
person = Person("John")

# Call the greet method
print(person.greet())  # Output: Hello from Decorator!

"""18. Property Decorators: @property, @setter, and @deleter
Assignment:
Create a class Product with a private attribute _price. Use @property to get the price, @price.setter to update it, and @price.deleter to delete it.
"""

class Product:
    def __init__(self, name, price):
        self.name = name
        self._price = price  # Private attribute

    # Getter: @property to access the price
    @property
    def price(self):
        print("Getting price...")
        return self._price

    # Setter: @price.setter to update the price
    @price.setter
    def price(self, new_price):
        if new_price < 0:
            raise ValueError("Price cannot be negative")
        print("Setting price...")
        self._price = new_price

    # Deleter: @price.deleter to delete the price
    @price.deleter
    def price(self):
        print("Deleting price...")
        del self._price


# Example usage:
product = Product("Laptop", 1000)

# Access the price (using the getter)
print(product.price)  # Output: Getting price... 1000

# Update the price (using the setter)
product.price = 1200  # Output: Setting price...
print(product.price)  # Output: Getting price... 1200

# Try deleting the price (using the deleter)
del product.price  # Output: Deleting price...

# Try to access the price after deletion (this will raise an error)
# print(product.price)  # Uncommenting this will raise an AttributeError since the price is deleted.

"""19. callable() and __call__()
Assignment:
Create a class Multiplier with an __init__() to set a factor. Define a __call__() method that multiplies an input by the factor. Test it with callable() and by calling the object like a function.
"""

class Multiplier:
    def __init__(self, factor):
        self.factor = factor  # Set the factor during initialization

    def __call__(self, number):
        return number * self.factor  # Multiply the input by the factor


# Example usage:
# Create an instance of Multiplier with a factor of 3
multiplier = Multiplier(3)

# Check if the object is callable using callable()
print(callable(multiplier))  # Output: True

# Call the object like a function
result = multiplier(5)  # This uses the __call__ method
print(result)  # Output: 15 (5 * 3)

"""20. Creating a Custom Exception
Assignment:
Create a custom exception InvalidAgeError. Write a function check_age(age) that raises this exception if age < 18. Handle it with try...except.
"""

# Define a custom exception
class InvalidAgeError(Exception):
    pass

# Function to check age
def check_age(age):
    if age < 18:
        raise InvalidAgeError("Age must be 18 or older.")  # Raise custom exception if age is less than 18

# Example usage:
try:
    age = 15
    check_age(age)  # This will raise InvalidAgeError because age < 18
except InvalidAgeError as e:
    print(f"Error: {e}")  # Handle the custom exception and print the error message

"""21. Make a Custom Class Iterable
Assignment:
Create a class Countdown that takes a start number. Implement __iter__() and __next__() to make the object iterable in a for-loop, counting down to 0.
"""

class Countdown:
    def __init__(self, start):
        self.start = start  # Initialize with a start number

    def __iter__(self):
        self.current = self.start  # Set the current number to the start value
        return self  # Return the iterator object itself

    def __next__(self):
        if self.current <= 0:
            raise StopIteration  # Stop iteration when the countdown reaches 0
        else:
            self.current -= 1  # Decrement the counter
            return self.current  # Return the current countdown value


# Example usage:
countdown = Countdown(5)

# Using the countdown object in a for-loop
for number in countdown:
    print(number)